.. _`EveryBlock`: http://www.everyblock.com/

.. |everyblock-intro| replace::
  `EveryBlock`_ is a website that filters an assortment of local news by
  location so you can keep track of what's happening on your block, in your
  neighborhood and all over your city. Made possible by a grant from the
  Knight Foundation, EveryBlock seeks to solve the problem of answering the
  question of "What's happening in my neighborhood?" A key aspect of any
  local data problem is good maps – and when EveryBlock wanted maps, they
  used OpenLayers.
